# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3be8bf563607a829a432e4e56b74ccfe73c0947e11bf6799dd77593b7549ddb173f821465fe01e79b6ee12e53e81ca0ae7df426ccf1a6f290af892074d67d4b

test:
  secret_key_base: b6d481731375d1377122f1bd30a01d0adb01f6db56513260561a15e298464c13debeede1aade49c07094ecacba955ef281e89cebed85e37250e3a968e3f29df3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
